- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Add the br_netfilter module at runtime
    community.general.modprobe:
      name: br_netfilter
      state: present
  - name: Install pigz
    package:
      name: pigz
      state: present
  - name: Add br_netfilter modules persistent
      
